version: 1.0.{build}
clone_folder: C:\Fruit
environment:
  PYTHON3_PATH: C:\Python36
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    CMAKE_PATH: 'C:\Program Files (x86)\CMake\bin'
    CMAKE_GENERATOR: 'Visual Studio 14 2015 Win64'
    VCVARSALL_DIR: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC'
    ADDITIONAL_CMAKE_ARGS: '-DFRUIT_USES_BOOST=False'
    CONFIGURATION: Debug
build_script:
- cmd: cmd /c C:\Fruit\extras\scripts\postsubmit.bat
